# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: B체ndnis Feuerundflamme
email: kontakt@feuerundflamme.xyz
lang: de
description: >- # this means to ignore newlines until "baseurl:"
  Das B체ndnis Feuer&Flamme engagiert sich am Dragonerareal mit Workshops rund um den offenen Keramiktreff, Back- und R채ucherhappenings am Backhauswagen und Einladungen zum gemeinsamen Kochen und Essen mit der Zusammenk체che.
baseurl: ""
url: "feuerundflamme.xyz"

permalink: /:year/:month/:day/:title:output_ext

# Fixed tiles in the home page
collections:
  fixed:
    output: true
    permalink: /:name

future: true

# Build settings
theme:
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "fixed"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "event"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME
